services:
  fivesec-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: fivesec-nginx:latest
    ports:
      - 8080:80
      - 8443:443
    networks:
      - opensearch-net
    volumes:
      - ./logs:/var/log/nginx
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin
    container_name: logstash
    volumes:
      - ./logs:/var/log/nginx
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - opensearch-net
    depends_on:
      - fivesec-nginx
  opensearch-node1:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_INSTALL_DEMO_CONFIG=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - ./opensearch_node_1.yml:/usr/share/opensearch/config/opensearch.yml:ro
      - ./opensearch-data-1:/usr/share/opensearch/data
      - ./certs:/usr/share/opensearch/config/certificates:ro
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_INSTALL_DEMO_CONFIG=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opensearch_node_2.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch-data-2:/usr/share/opensearch/data
      - ./certs:/usr/share/opensearch/config/certificates:ro
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
      - DISABLE_INSTALL_DEMO_CONFIG=false
    expose:
      - "5601"
    volumes:
      - "./certs:/usr/share/opensearch-dashboards/config/certificates:ro"
      - "./opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net: